### ISSUE TITLE
'Can See Submission Data' not working(?)

### ISSUE THREAD

**Issue by Mikalicious** [No3x/wp-mail-logging#27]
Hi,

First of all, thank you very much for the great plugin. I would like to use the 'Can See Submission Data' function but it is not working. I managed to see 'WP Mail Logging' when login as admin. I have created a custom role ('Manager') and set the minimum role to 'Create User' but it did not show when login as manager. It is same even if I set to 'Manage Options'. Can you please kindly check?

My Wordpress version is 4.1 and using WP-Mail Logging version 1.4. Thank you very much!

**Comment by No3x** [comment]
Oops! Thanks four your report. I already found the cause. If I'm right you should see the contents when accessing http://<website>/wp-admin/admin.php?page=wpml_plugin_log with the right restictions applied.

**Comment by Mikalicious** [comment]
Hi,

Thanks for your quick reply! I tried to access http://website/wp-admin/admin.php?page=wpml_plugin_log when login as 'Manager' but it showed 'You do not have sufficient permissions to access this page.' I have set the minimum role to 'Add User' and applied to 'Manager'. Does this plugin may not work 'User Role Editor' plugin by chance? Thank you No3X.

**Comment by Mikalicious** [comment]
Hi,

Just to update, I tried with default Wordpress role (Contributor) with minimum role set to 'Edit Post' and the result is 'You do not have sufficient permissions to access this page.' when accessing  http://website/wp-admin/admin.php?page=wpml_plugin_log. Thank you!

**Comment by No3x** [comment]
The user accessing the page must have the capability (so one of https://codex.wordpress.org/Function_Reference/current_user_can#Capabilities_Parameters) set in the plugin settings. Please check your Manager has the cap 'create_users'.

**Comment by No3x** [comment]
I would be happy if you could try this beta before I publish this fix to the wordpress plugin repository: https://github.com/No3x/wp-mail-logging/releases/tag/beta%2F1.4.1R1

**Comment by Mikalicious** [comment]
Hi Zoller / No3x!

Good day. Thank you very much for the beta file, the plugin worked fine now. I tested with default role and custom role and it managed to show in admin! 

Very great plugin! Thank you!

**Comment by No3x** [comment]
Thanks for testing this version. The results are matching with my observation. I will push this to the WordPress plugin repository later. You can revert to an official version or stay with this version. You will receive updates as normal in both cases. If you choose the latter one you should delete .travis.yml, phpunit.xml, tests and bin at least.
