### ISSUE TITLE
Please remove Settings admin menu item

### ISSUE THREAD

**Issue by tripflex** [No3x/wp-mail-logging#28]
Please add the option to disable the admin menu settings link/icon.  I hate it when plugins add menu items to admin bar and do not have the option to disable it.  Thanks

<img src="https://smyl.es/img/Selection-04-17-2015-156.png">

**Comment by No3x** [comment]
I don't know this bar.

**Comment by No3x** [comment]
https://github.com/No3x/wp-mail-logging/blob/master/inc/redux/options-init.php#L373
I will disable it in the next release. Never noticed this in the frontend and it's not that useful thought. Thanks

**Comment by holygekko** [comment]
would it be possible to remove the redux framework altogether? It adds 8.3MB to a 735KB plugin ;)
