### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by BoiteAWeb** [No3x/wp-mail-logging#31]
Hello, i'm Julio Potier, a french Web Security Consultant.

I found some vulnerabilities in your plugin and i don't want to disclose this publicly.

Can you contact me for more informations at julio @boiteaweb.fr

Thanks!

**Comment by No3x** [comment]
Received details and working on a solution to make the plugin secure.

**Comment by No3x** [comment]
Cherry picked some fixes from current master to release a security patch. Fixed in https://github.com/No3x/wp-mail-logging/tree/release/1.5.1
