### ISSUE TITLE
After Update Blank content after clicking View

### ISSUE THREAD

**Issue by pianckim** [No3x/wp-mail-logging#39]
Hi,

After your recent Updating your plugin WP Mail Loggin I have Blank content after clicking View for all items in the Mail Log.  I am running Version: 1.6.1 and the latest version of WP.

My Site is http://pianc.net/ 

Can you take a look?

Thank you,

Kim

**Comment by No3x** [comment]
Hi. What version of WordPress and PHP are you running? 
Any error in the log?
The url doesn't help since the plugin is located in the admin area.

**Comment by pianckim** [comment]
Thanks for getting back to me! We are using WordPress 4.5.3. How can I determine which version of PHP my web host is using? Attached is the error log.

 

 

Kim

919-247-4045

**Comment by No3x** [comment]
Something with the log went wrong.

**Comment by pianckim** [comment]
What should I do?

 

Kim

919-247-4045

**Comment by pianckim** [comment]
Here is the error log again in txt format in case you could not access it yesterday.

 

Kim

919-247-4045

**Comment by No3x** [comment]
The logs are from March.
There is also no entry with wp-mail-logging.

**Comment by pianckim** [comment]
The most recent errors are at the bottom of the file but you are correct there are no errors related to WP Mail Logging except in May 2016.  

 

Do you think I should go back and install the last version that worked for me (I see this on your plugin page)?  Other Thoughts??

 

Kim

919-247-4045

**Comment by No3x** [comment]
I think you should ask somebody to verify errors are logged and get logs for you.

**Comment by pianckim** [comment]
OK will do.

 

Kim

919-247-4045

**Comment by pianckim** [comment]
Just applied the update and all my email content is back.  Thanks so very much!!

 

Kim

919-247-4045

**Comment by No3x** [comment]
I [did not change anything](https://github.com/No3x/wp-mail-logging/compare/release/1.6.1...release/1.6.2) related to this. I think this was a caching issue then.

Happy to hear it works fine now!
