### ISSUE TITLE
Scroll issue with WP Mail logging

### ISSUE THREAD

**Issue by App2build** [No3x/wp-mail-logging#40]
When scrolling my screen the row are moving, but the view button is not moving with the rows.
![screen shot 2016-09-16 at 23 15 47](https://cloud.githubusercontent.com/assets/15180334/18601524/9524673a-7c63-11e6-8bbb-ac7bf5cceaf4.png)

**Comment by No3x** [comment]
Did you an update recently?

**Comment by App2build** [comment]
Yes, Wordpress to newest version

**Comment by App2build** [comment]
4.6.1

**Comment by No3x** [comment]
And the plugin, too?

**Comment by App2build** [comment]
plug-in 1.6.2

**Comment by No3x** [comment]
Did you update the plugin to  1.6.2, too? What browser are you using?

**Comment by App2build** [comment]
plug in was on 1.6.2.  Only updated Wordpress. I use Firefox and Chrome. Both same result

**Comment by No3x** [comment]
I'll check on a test site right now with latest wp version.

**Comment by App2build** [comment]
Also same result on Safari

**Comment by No3x** [comment]
No Issues with 1.6.2, 4.6.1, Windows Chrome

**Comment by No3x** [comment]
No issues with safari either.

**Comment by App2build** [comment]
That is strange. 
Oke.
Let me then investigate why it is going wrong at mine website.
Thanks for testing it

**Comment by No3x** [comment]
Thanks for reporting and force me to test with the latest wp version. Maybe you can set up a clean wp install on your site or something like that.

**Comment by No3x** [comment]
Closed due lack of coop
