### ISSUE TITLE
Plugin Compatability

### ISSUE THREAD

**Issue by UserName011** [No3x/wp-mail-logging#47]
Does the plugin compatible with wordpress 4.7?

In the plugin page it says "Compatible up to: 4.6.1"
this results a conflict for all who uses this plugin as in their site they see:
Compatibility with WordPress 4.7: Unknown
Which tells them not to update because it's not compatable

**Comment by No3x** [comment]
Yes it is. It will be changed to be clearly compatible in the next version. By the way that's just a hint.
