### ISSUE TITLE
Remove entire mail table from database

### ISSUE THREAD

**Issue by tripflex** [No3x/wp-mail-logging#49]
So I had an issue (assuming its from having an old install) where i was getting errors about the `host` column not existing in the database table ... tried removing the entire plugin, reset all settings, and couldn't find anything in the settings, to actually remove the database table.

Would be good to have a setting or action button in settings to remove and re-setup the db table for those who may not know how to do it otherwise (plus just good to have)

**Comment by No3x** [comment]
Did the cleanup option not work for this? I have "unit tests" (more likely integration tests) for this.

**Comment by No3x** [comment]
Just tested again with the mentioned cleanup setting.
