### ISSUE TITLE
Please add language files

### ISSUE THREAD

**Issue by xxxycl** [No3x/wp-mail-logging#51]
Can u add default language files? 
Then we can translate the language files.

**Comment by No3x** [comment]
I will add the pot right now. Please let me know if something is missing or not ok with the translation strings. (I'v never translated a plugin but prepared a translation since the beginning).
What languages do you want to add? Will you contribute the translation to this repository?

**Comment by No3x** [comment]
Please let me know if I can help you with something. A good starting point is https://guides.github.com/introduction/flow/

**Comment by No3x** [comment]
Do you plan a contribution in the next few days? I have waited for your commit to release a new version.
Please give feedback if your commit should be part of 1.8.0 or a subsequent release.

**Comment by xxxycl** [comment]
All right, I'll add the files in these two days.
Latest addition in February 15, 2017.

**Comment by xxxycl** [comment]
Hello, I have done the translation file well, but I have encountered a problem with the submission and I am trying to use git. If you need this file urgently, I can send it to you by email.

**Comment by xxxycl** [comment]
The file has been submitted, please check it. If it is correct, please close this issues.

**Comment by No3x** [comment]
Thanks for your contribution!
