### ISSUE TITLE
"Plugin could not be activated because it triggered a fatal error."

### ISSUE THREAD

**Issue by chris-hewitt** [No3x/wp-mail-logging#53]
When attempting to activate the plugin:

Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected '[' in /var/www/web/pph/wp-content/plugins/wp-mail-logging/WPML_Email_Log_List.php on line 88 
Fatal error: syntax error, unexpected '[' in /var/www/web/pph/wp-content/plugins/wp-mail-logging/WPML_Email_Log_List.php on line 88

wp-mail-logging 1.7.0
WordPress 4.7.2
PHP 5.3.1

**Comment by No3x** [comment]
You need php 5.4 at least
