### ISSUE TITLE
code which displayed as text

### ISSUE THREAD

**Issue by UserName011** [No3x/wp-mail-logging#55]
Why does it display it like this?
`\n` should be enter isn't it?
![66](https://cloud.githubusercontent.com/assets/22069599/23225312/219d8f72-f93a-11e6-8d0b-7350958b4b0a.png)

**Comment by No3x** [comment]
What display mode did you select?

**Comment by UserName011** [comment]
@No3x How can I see that?

**Comment by No3x** [comment]
Yeah I just realised that's the view of the email list (and not the detail view). What do you expect to see instead?

**Comment by UserName011** [comment]
First it should be in 3 rows:
From:  email
Reply-To: email
Content-Type: dunno what needs to be here but i'm sure that `text/html,\ncharset=utf-8` doesn't mean anything to the user.

**Comment by No3x** [comment]
My users are primary developers I guess. I think that's relevant to see.

**Comment by UserName011** [comment]
@No3x  This has no meaning. At the front side of the site we should see the result of the code not the code itself.

`\n` is coding key which should be translated to the command `Enter`.
`charset=utf-8` should tell the browser to display the page with `[UTF-8](https://en.wikipedia.org/wiki/UTF-8)`  encoding.

It seems like the plugin takes a text which has code in it and simply display it as is rather than eval it.

**Comment by No3x** [comment]
Header values are delimited by a line-break. I want to show the raw-header information in this column.
