### ISSUE TITLE
How does the email saved in the database?

### ISSUE THREAD

**Issue by UserName011** [No3x/wp-mail-logging#56]
I want to import the emails sent from WordPress to my own database.
Where does the data from this plugin saved?
I want to write an SQL which shows the emails.. then I can easily import the data.

**Comment by No3x** [comment]
Hi @UserName011,
the mails are [stored in a table](https://github.com/No3x/wp-mail-logging/blob/7b02107889e53a73704f92ee3953fa18b374150c/WPML_Plugin.php#L46) called 
```php 
"{$wpdb->prefix} . 'wpml_mails"
```
The [schema is really simple](https://github.com/No3x/wp-mail-logging/blob/7b02107889e53a73704f92ee3953fa18b374150c/WPML_Plugin.php#L47-L58):
```sql
`mail_id` INT NOT NULL AUTO_INCREMENT,
`timestamp` TIMESTAMP NOT NULL,
`host` VARCHAR(200) NOT NULL DEFAULT '0',
`receiver` VARCHAR(200) NOT NULL DEFAULT '0',
`subject` VARCHAR(200) NOT NULL DEFAULT '0',
`message` TEXT NULL,
`headers` TEXT NULL,
`attachments` VARCHAR(800) NOT NULL DEFAULT '0',
`error` VARCHAR(400) NULL DEFAULT '',
`plugin_version` VARCHAR(200) NOT NULL DEFAULT '0',
PRIMARY KEY (`mail_id`) 
```
I don't know what you really want to do - so I will provide you some strategies I'm aware of. You can choose what fits your needs.

## Strategy 1 - PHP

If you have the plugin installed where you start creating your export script in php you can simple use the mail model class!
```php
use No3x\WPML\Model\WPML_Mail as Mail;

Mail::find_one_by($property, $value)
Mail::find_one($id)
Mail::all()
```
With this you can build things like:
```php
$mail = Mail::find_one(1);
```
or
```php
$mails = Mail::query()
            ->search( $search )
            ->sort_by( $orderby )
            ->order( $order )
            ->limit( $per_page )
            ->offset( $offset )
            ->find();
```
or propably what you want to do:
```php
foreach( Mail::all() as $mail ) {
    // access the properties you need
    $mail->get_receiver(), $mail->get_subject(), $mail->get_message(), $mail->get_headers(), $mail->get_attachments()
    // provide to export process
}
```

## Strategy 2 - REST API
There is a REST API Endpoint in the code. If you need this please let me know to provide you more detals on this.

## Strategy 3 - Plain SQL
If you really want to just use sql it's just a select query:
```sql
"SELECT * FROM {$wpdb->prefix} . 'wpml_mails"
```

(the code is untested and contains pseudo-code)

**Comment by UserName011** [comment]
Thanks.
Is there a way to also save which plugin triggered the email?
Also, what is the meaning of the plugin_version field? why is it needed per email?

**Comment by No3x** [comment]
No the source is not saved. You could do this by saving the call stack maybe.
The `plugin_version` field is stored for back compatibility reasons: 
Imagine the simple case: a mail was logged with plugin version 1: the path to an attachment was stored relative to the WP_CONTENT dir.
In version 2 the path is stored relative to WP_UPLOAD dir. I need to distinguish therefore to display mails from version 1 to render them accordingly with version 2.
