### ISSUE TITLE
Fatal error: Uncaught phpmailerException: Invalid address: (setFrom)

### ISSUE THREAD

**Issue by bluantinoo** [No3x/wp-mail-logging#58]
Error when trying to resend one or more emails:

`Fatal error: Uncaught phpmailerException: Invalid address: (setFrom) info@mydomain.it,\nReply-To: info@mydomain.it,\nBcc: notifiche@mydomain.it,\nContent-type: text/html; charset=UTF-8 in /home/wwwxxxx/public_html/wp-includes/class-phpmailer.php:1023 Stack trace: #0 /home/wwwxxxx/public_html/wp-content/plugins/smtp-mailer/main.php(612): PHPMailer->setFrom('info@mydoma...', 'XXXX XXX X...', false) #1 /home/wwwxxxx/public_html/wp-content/plugins/wp-mail-logging/WPML_Email_Log_List.php(425): wp_mail('my.email@i...', 'Contatto Ricevu...', '<html>\r\n\t<head>...', Array, Array) #2 /home/wwwxxxx/public_html/wp-content/plugins/wp-mail-logging/WPML_Email_Log_List.php(412): No3x\WPML\WPML_Email_Log_List->resend_email(Object(No3x\WPML\Model\WPML_Mail)) #3 /home/wwwxxxx/public_html/wp-content/plugins/wp-mail-logging/WPML_Email_Log_List.php(154): No3x\WPML\WPML_Email_Log_List->process_bulk_action() #4 /home/wwwxxxx/public_html/wp-content in /home/wwwxxxx/public_html/wp-includes/class-phpmailer.php on line 1023`

I'm using the following plugins:

- SMTP Mailer 
- Gravity Forms
- WPML

On main settings I use an email, but on gravity forms I use another one as sender, this other address is SMTP authenticated via SMTP Mailer.

if I use this filter:

add_filter( 'wp_mail_from', function() {
    return 'info@mydomain.it';
} );

with the same address I use in gravity as sender, error is no more there.

**Comment by No3x** [comment]
The first suspicious thing I see is the `Invalid address: (setFrom) info@mydomain.it`. It looks like a directive of gravity forms to do something with the from field. Can you send a database dump of this specific entry (especially the headers)? This would help a lot

**Comment by bluantinoo** [comment]
It happens with every single email I try to resend, not just a specific one.
info@mydomain.it is a placeholder i used instead of real email address.

Gravity Forms Modules use all this info@mydomain.it as sender, and it's authenticated with SMTP Mailer.
While in WP general settings there's another email (notifications@anotherdomain.com)

Anyway, here's the dump of a single row of mails table https://pastebin.com/EvWH2wDV

**Comment by No3x** [comment]
Of course you have replaced the mail address with a fake. But I meant that `(setFrom)`.

Db entry looks fine.
Unfortunately when resending the mail I can not fulfill all precondition that where met when the mail was originally sent. Imagine a hook on the phpmailer that is set when gravity forms sends a mail. If wpml resends then it does not set this specific hook. This can lead to such issues I guess.

**Comment by No3x** [comment]
The issue is: it literally tries to set the from header to this: `info@mydomain.it,\nReply-To: info@mydomain.it,\nBcc: notifiche@mydomain.it,\nContent-type: text/html; charset=UTF-8`.

This is because the wp_mail method has no chance to explode the header entries. Because in the database the line breaks are stored as text. If they are passed to the wp_mail function they are flatterned by `\n` but they need to be flatterned by `\\n`. Further it is convenient to pass an array to the wp_mail method. For this the array entries must not end with `,`.

Can you please patch your resend_email method in the WPML_Email_Log_List.php  and test again?
```
   /**
     * Send logged email via wp_mail
     * @param WPML_Mail $mail the email object to resend
     * @since 1.8.0
     */
    function resend_email( $mail ) {
        $headers = explode( "\\n", str_replace( "\\r\\n", "\\n", $mail->get_headers() ) );
        foreach ($headers as &$header) {
            $header = rtrim($header, ",");
        }
        wp_mail( $mail->get_receiver(), $mail->get_subject(), $mail->get_message(), $headers, $mail->get_attachments() ) ;
    }
```

**Comment by bluantinoo** [comment]
Good news No3x, it works. Both issues (#58 and #59) solved with this patch.
Thanks for your time!

**Comment by No3x** [comment]
Glad to hear! You are welcome. I will commit this soon and release a new plugin version.

**Comment by bluantinoo** [comment]
:thumbsup:

**Comment by No3x** [comment]
Please check your pastebin because it maybe contains sensitive data as mail and domain.
