### ISSUE TITLE
Wrong Content-Type When Resending Emails

### ISSUE THREAD

**Issue by bluantinoo** [No3x/wp-mail-logging#59]
When I use the "resend" feature, the message body arrives as HTML code,
infact in the message head I see:

`Content-Type: text/plain;`

While original emails have:

`Content-Type: text/html;`

EDIT: I looked in DB, and in wpml_mails table "headers" are correct. So Don't understand how it becomes plain text when sending.

**Comment by bluantinoo** [comment]
Using this filter solves

```
add_filter( 'wp_mail_content_type', function( $content_type ) {
	return 'text/html';
});
```

But it's just a temporary hack when I need to resend some mails.

**Comment by No3x** [comment]
Actually the same headers are used to resend the mail (as stored in the database). This must be corrupted by SMTP Mailer or another plugin I guess.

**Comment by bluantinoo** [comment]
Infact I saw the code, i see that headers are correctly stored in db and they are normally called by $mail->get_headers()
but somehow even it is HTML mails are sent as PLAIN TEXT :(

I don't have any other plugin that messes around with emails, just Gravity and SMTP Mailer.

**Comment by No3x** [comment]
The same [explanation](https://github.com/No3x/wp-mail-logging/issues/58#issuecomment-306458250) applies here. As workaround you could resend the mail on another datalevel. There are mailserver that allow resending too. 

I'm sorry this doesn't work out of the box currently. Fixing this would require a tight coupling on gravtiy-forms and an adaptation for all plugins that send mails. This is insane.

**Comment by bluantinoo** [comment]
don't worry, I just felt right to report this. 
I've used both gravity and wp mail logging altogether in a lot of wp installations, and i never saw this.

**Comment by No3x** [comment]
So this works fine on another site/server?

**Comment by bluantinoo** [comment]
yes, don't know how many because i don't need to debug email for all websites, but I've used the resend feature other times in the past and it was working.

**Comment by No3x** [comment]
Can you check if php $_SERVER['SERVER_NAME'] is set?

**Comment by bluantinoo** [comment]
I'm sorry for my stupid question, but: where should I perform this check?

**Comment by No3x** [comment]
Never mind. This sould be fixed with #[58](https://github.com/No3x/wp-mail-logging/issues/58#issuecomment-306515183).
