### ISSUE TITLE
Side effect on French quotation marks not set when plugin is enabled

### ISSUE THREAD

**Issue by geoffreybr** [No3x/wp-mail-logging#60]
When Wordpress is set in French, the "English quotations marks" are replaced by the « French quotation marks ». Here is a screenshot with the quotation marks highlighted in yellow:

![screenshot-plugin-disabled](https://user-images.githubusercontent.com/5603223/27454108-0b4e6698-5799-11e7-99ad-89df0797f8ed.jpg)

**When I enable the wp-mail-logging plugin, it does not work:**

![screenshot-plugin-enabled](https://user-images.githubusercontent.com/5603223/27454141-3484c2d2-5799-11e7-94fc-e2e3ff45c0fd.jpg)

Do you have an idea why? And how can I solve it?
Thanks,

**Comment by No3x** [comment]
Hi @geoffreybr 
this could be related to the [charset of the table](https://github.com/No3x/wp-mail-logging/blob/master/WPML_Plugin.php#L59).
You could change this to another utf_8_* in a test environment to check if this is the reason.

**Comment by geoffreybr** [comment]
Hi @No3x 
Thanks for your fast answer!
I tried with `DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci` as it is in the posts table. But nothing changed. `utf8_general_ci` is used by other plugins without any problem.

**Comment by No3x** [comment]
Okay, then it seems to be an issue in the code. I would need to find the location where this replacement happens. 
Are the results different when you view the mail in a different format like raw or json?

**Comment by geoffreybr** [comment]
> Are the results different when you view the mail in a different format like raw or json?

I'm not sure to well understand the question, but that's probably because there is a misunderstanding from my first post. The quotation marks I'm speaking about are the ones of the articles / the posts and not in the mail logs. That's why it's an issue for our website. You can see the example here : http://www.rue89strasbourg.com/big-bang-majorite-municipale-strasbourg-en-marche-122331

**Comment by geoffreybr** [comment]
This transformation is made by [wptexturize](https://codex.wordpress.org/Function_Reference/wptexturize). But it looks like it is done in the English way because we have curly quotation marks instead of French quotation marks.

**Comment by No3x** [comment]
Ahh it's on your site. I understood it's when viewing sent html mails. I'm not aware of any changes of my plugin in the content or output of the CMS. I use a framework for settings that is called Redux. It is really big and might affect such a thing. If you do have a testing environment you could install an older version of the plugin without redux (version 1 or so). But it uses a differend table schema. So make sure there is not wp_mails table already in the test env.

**Comment by geoffreybr** [comment]
Yes that's it: I noticed that v1.4.0 contained introduction of redux, so I installed v1.3.2 and it is okay now.

**Comment by No3x** [comment]
Well, then you should consult the redux support. Or find another plugin that has redux included and see if it behaves the same.

**Comment by geoffreybr** [comment]
I just tried installing [redux-framework plugin](https://wordpress.org/plugins/redux-framework/) enabling the demo mode and the quotation marks are correct.
I just double-checked and it is introduced in v1.4.0 because of redux. If I comment [line 44 of `inc/redux/options-init.php`](https://github.com/No3x/wp-mail-logging/blob/release/1.4.0/inc/redux/options-init.php#L44), the display is okay. So I continue my investigation to find out where the problem come from in the current version.

**Comment by geoffreybr** [comment]
Ok I got it : I have no idea why, but when I comment `echo $this->theme->display( 'Description' );` in [line 218 of `inc/redux/WPML_Redux_Framework_config.php`](https://github.com/No3x/wp-mail-logging/blob/master/inc/redux/WPML_Redux_Framework_config.php#L218). This solves my problem. Do you understand why?

**Comment by No3x** [comment]
This sounds funny! There is so much stuff in this file that is not really needed to configure redux. I think you replace the contents with this: https://gist.github.com/No3x/a6894ec8964e9d5a922601339b501c1a

**Comment by geoffreybr** [comment]
Sehr gut! This works well for me :smiley:! Thanks!

**Comment by No3x** [comment]
Hey you actually speak really good german! Cool so you can do a PR or I will change this within the next 3 weeks (I currently don't have much time for testing a new release).

Let's keep this open until it's fixed in the sources.
