### ISSUE TITLE
Conflict with Pricing Deals Plugin

### ISSUE THREAD

**Issue by varktech** [No3x/wp-mail-logging#69]
Hi,
There looks to be a conflict between WP Mail Logging and one of my plugins, https://wordpress.org/plugins/pricing-deals-for-woocommerce/ .  Various deals consistently fail, particularly those activated with Woo Coupons ( https://www.varktech.com/documentation/pricing-deals/introrule/#discount.discountcoupon ). 

Currently, any customer having both of our plugins has to shut off WP Mail Logging, in order to use Pricing Deals.  Could you please take a quick look, to see if there's anything you might suggest I do to allow our 2 plugins to coexist peacefully?

Thanks
Mark

**Comment by No3x** [comment]
What does fail mean? Can you elaborate and give precise instructions to reproduce this? I'm not familiar with this plugins.

**Comment by varktech** [comment]
Hi,
Thanks for responding so quickly!  If you use Pricing Deals and set up a simple discount activated through a WOO coupon, when both plugins are active, the deal fails to process when the coupon is presented. 
Mark

**Comment by No3x** [comment]
Sorry I can't figure out how to configure all this stuff to reproduce the error. I just installed WooCommerce and let it create sample products and installed your plugin.

**Comment by varktech** [comment]
If you drop me a line at vark [ at ] at varktech [ dot ] com, we can do a skype session and work it through (if that works for you...).

**Comment by No3x** [comment]
We were not able to reproduce on my c9 instance. Are there any news related to the incompatibility?

**Comment by varktech** [comment]
Sorry, no... can't seem to localize it.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_2467257059641486881_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
