### ISSUE TITLE
\n in header column

### ISSUE THREAD

**Issue by jrfoell** [No3x/wp-mail-logging#70]
I noticed a '\n' in the header column in wp-admin. I believe it's b/c the string in implode here: https://github.com/No3x/wp-mail-logging/blob/master/WPML_Plugin.php#L198 (and in extractReceiver() above it) are encased in a single-quote string rather than a double-quote string, which should allow the \n character to get rendered as desired.

**Comment by No3x** [comment]
Duplicate of #55?

**Comment by jrfoell** [comment]
Possibly, so it's done that way on purpose?

**Comment by No3x** [comment]
As stated in the other issue:
> Converting \n to line breaks would inflate the row height.
I want to show the raw-header information in this column.

But you can try to convince me with a better solution. So you would like to see each entry row by row?

**Comment by jrfoell** [comment]
I think it just caught me off-guard b/c it looked weird. I would suggest if you keep it to put a note in the FAQ about it :)

**Comment by No3x** [comment]
Yeah, it looks pretty weird but I don't have a better solution. I could use `,` as delimiter or `<pre>`.
