### ISSUE TITLE
Redux side-effect: PHP Notice:  Undefined index: REMOTE_ADDR

### ISSUE THREAD

**Issue by lkraav** [No3x/wp-mail-logging#72]
```
PHP Notice:  Undefined index: REMOTE_ADDR in plugins/wp-mail-logging/lib/vendor/redux-framework/inc/class.redux_helpers.php on line 69
```
#36 probably can't be helped due to problem size, but maybe we can patch this notice out?

It's probably triggered when wp-cron is triggered via server side cron, in which case there is no remote request.

This is probably the correct return condition:

```php
return ( ! isset( $_SERVER['REMOTE_ADDR'] ) || $_SERVER['REMOTE_ADDR'] === '127.0.0.1' || $_SERVER['REMOTE_ADDR'] === 'localhost' ) ? 1 : 0;
```

**Comment by No3x** [comment]
Hi @lkraav,

can you tell how the cronjob is executed? `$_SERVER['REMOTE_ADDR']` should always be set, if the script is executed via the webserver. If it's executed by php cli it is not set AFAIK.

Maybe the best solution is to change the cronjob to make an HTTP request via wget or curl.
I don't want to maintain manual patches to the redux library, although it's included as copy in the repository. So maybe we should ask upstream at the redux team about [it](https://github.com/reduxframework/redux-framework/blob/3.6.5/ReduxCore/inc/class.redux_helpers.php#L69) to apply a defensive check.

**Comment by lkraav** [comment]
It is not going through the webserver, because it really doesn't have to. I tend to agree with https://pressjitsu.com/blog/wordpress-cron-cli/ there's no point in locking up `php-fpm` workers and get subjected to all related limitations, when for whatever needs to be done, it can safely run in the background for however long it wants.

I'm doing:

```
*/5 * * * * /usr/local/bin/php /home/convers/www/institute/wp-cron.php
```

Let's help Redux get this right.

**Comment by No3x** [comment]
Hi @lkraav thanks for the link. I have never thought about the advantages about bypassing the webserver.
> I'm doing:
`*/5 * * * * /usr/local/bin/php /home/convers/www/institute/wp-cron.php`

This behaviour is as expected. 

> Let's help Redux get this right.

Would you like to create a PR on the redux repo? I will update redux when the fix is included in a release.

**Comment by No3x** [comment]
Hi @lkraav,
any updates on this?

**Comment by No3x** [comment]
This is fixed upstream. 

- [ ] Need to upgrade version for the next release
