### ISSUE TITLE
HTML comments not interpreted in HTML preview

### ISSUE THREAD

**Issue by michaelrimbach** [No3x/wp-mail-logging#77]
Hi,

big thanks for this plugin, I use it nearly every day.

I have discovered a small bug: HTML comments are not right interpreted. For example if you send an email with a comment  the plugin encodes it to --&gt; and then the html preview is not working correct anymore. 

Maybe you could fix it in a future version. Thanks!

Michael

**Comment by No3x** [comment]
I sent a test mail with different quoatation marks copied from Wikipedia. 
The input:
![unbenannt](https://user-images.githubusercontent.com/2690708/44781601-23894980-ab85-11e8-8f90-a48b2004bf8f.JPG)

The result:
![unbenannt](https://user-images.githubusercontent.com/2690708/44781623-30a63880-ab85-11e8-904d-50121097f6ba.JPG)

Please provide more details to reproduce.

**Comment by No3x** [comment]
Hi @michaelrimbach,

please ignore the previous answer. 
I tested the following message:
```
<!-- Comment -->
<b>H</b>ello World
```
And the output with the html renderer is:
**H**ello World
Please provide the exact HTML you have problems with or reduce to a short example that reproduces the issue.

**Comment by michaelrimbach** [comment]
Thanks for the fast response!

The "raw" code already have "&lt;!--" instead of "

FYI the mail looks good in my mail clients (with correct comments)
