### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by richardtape** [No3x/wp-mail-logging#81]
Fatal error: Class 'No3x\WPML\Pimple\Container' not found in /srv/users/serverpilot/apps/tigertool-wp/public/wp-content/plugins/wp-mail-logging/src/WPML_DI_Container.php on line 11

Running Version 1.8.5 downloaded from the wp.org repository.

WordPress 4.9.8.

I suspect this is an autoloading issue?

**Comment by richardtape** [comment]
Urgh. Please close and ignore. The `lib` directory wasn't correctly uploaded due to a `.gitignore`

Very sorry.

**Comment by No3x** [comment]
Oh that's good news because it sounded really bad. I was just about to spin up a fresh WP instance and try to reproduce.

Thanks for the feedback

**Comment by richardtape** [comment]
(just in case any intrepid folks stumble on this; it was caused by a global .gitignore file which `ignore`d all `vendor` directories)

Sorry for the panic @No3x
