### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by pgordalina** [No3x/wp-mail-logging#85]
My log shows an exclamation mark in the error field, but no error description. Can you fix this please or this expectable? Thanks!

**Comment by pgordalina** [comment]
https://ibb.co/jQGNCq

**Comment by pgordalina** [comment]
After checking on my desktop, this is a mobile issue only.

**Comment by No3x** [comment]
It's using an icon with html `title` attribute. Like here: https://www.w3schools.com/tags/att_title.asp
There is maybe a trick to view this from mobile too, although there is no real hover.
