### ISSUE TITLE
Default attachment icon not rendering

### ISSUE THREAD

**Issue by Spreeuw** [No3x/wp-mail-logging#90]
the default icon is set to `file` in [WPML_Attachment]( https://github.com/No3x/wp-mail-logging/blob/release/1.9.0/src/WPML_Attachment.php#L126) but this results in the class `fa-file-file-o` in the resulting icon element, which does not exist (this should be `fa-file-o`). This renders the attachments invisible.

**Comment by No3x** [comment]
I refactored that part recently. I must have introduced a bug.
